name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest


  

    steps:


    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Configurar variável de saída para o nome da imagem
      id: my_step
      run: echo "::set-output name=MINHA_VARIAVEL::${{ secrets.DOCKERHUB_USERNAME }}/dm_structure_stream_chain_txs:$(date +%s)"


    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t ${{ steps.my_step.outputs.MINHA_VARIAVEL }} .
        docker push ${{ steps.my_step.outputs.MINHA_VARIAVEL }}